# Generated by Django 3.0.8 on 2020-07-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verify_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_emp',
            name='avatar',
        ),
    ]
